- name: Set hostname based on tag_internaldns
  hostname:
    name: "{{internaldns}}"
  when: internaldns is defined

- stat:
    path: /etc/cloud/cloud.cfg
  register: cloud_cfg_file

- name: disable updating hostname in /etc/cloud/cloud.cfg
  lineinfile:
    dest: /etc/cloud/cloud.cfg
    regexp: 'update_hostname$'
    line: '# - update_hostname'
    backup: yes
  when: cloud_cfg_file.stat.exists
  tags: disable_cloud_cfg_hostname
