- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars_files:
   - ./env_vars.yml
  tasks:
  - name: AWS Generate Cloudformation Template
    template:
      src: ./files/cloud_providers/ec2_cloud_template.j2
      dest: ./ec2_cloud_template.yml
