#set ft=ansible
---
- name: get the default ip of localhost
  hosts: localhost
  tasks:
    - debug:
        var: ansible_default_ipv4.address

- name: Test access to bastion by setting motd
  hosts: bastion_host
  remote_user: cloud-user
  become: true
  vars_files:
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_vars.yml"
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_secret_vars.yml"
  tasks:
    - name: bastion ansible_host
      debug:
        var: ansible_host
    - name: bastion ip
      debug:
        var: ansible_default_ipv4.address
    - copy:
        content: "Welcome to Bastion. We hope you enjoy your stay.\n"
        dest: /etc/motd
      register: motd_changed
      until: motd_changed | success
      retries: 3
      delay: 25
    - debug:
        var: ansible_host


- name: Test access to www1 by setting motd
  hosts: www1-REPL.rhpds.opentlc.com
  remote_user: cloud-user
  become: true
  vars_files:
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_vars.yml"
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_secret_vars.yml"
  tasks:
    - name: www1 ansible_host
      debug:
        var: ansible_host
    - name: www1 ip
      debug:
        var: ansible_default_ipv4.address
    - copy:
        content: "Welcome to www1. Please be seated. Your server will be with you shortly.\n"
        dest: /etc/motd
      register: motd2_changed
      until: motd2_changed | success
      retries: 3
      delay: 25

- name: Test access to www2 by setting motd
  hosts: www2-REPL.rhpds.opentlc.com
  remote_user: cloud-user
  become: true
  vars_files:
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_vars.yml"
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_secret_vars.yml"
  tasks:
    - name: www2 ansible_host
      debug:
        var: ansible_host
    - name: www2 ip
      debug:
        var: ansible_default_ipv4.address
    - copy:
        content: "Welcome to www2. Please be seated. Your server will be with you shortly.\n"
        dest: /etc/motd
      register: motd3_changed
      until: motd3_changed | success
      retries: 3
      delay: 25
