#vim: set ft=ansible:
---
######################### Install Basic Packages

- name: Install nfs Packages
  include: ./packages.yml
  tags:
    - install_nfs_packages

######################### Config NFS Mount Storage

- name: config_nfs_mount_storage
  include: ./config_nfs_mount_storage.yml
  tags:
    - config_nfs_mount_storage

- name: create nfs exports
  include: ./nfs_exports.yml
  tags:
    - create_nfs_exports
