# vim: set ft=ansible:
---
- name: check if zabbix_agent_t is permissive
  shell: semanage permissive -l|grep zabbix_agent_t
  register: permissive
  ignore_errors: yes
  changed_when: false

- name: Set zabbix agent permissive in SElinux
  command: semanage permissive -a zabbix_agent_t
  when: permissive is failed
