# vim: set ft=ansible:
---

- name: list current repository files
  shell: "ls -1 /etc/yum.repos.d/"
  register: repodircontents
  tags:
    - configure_repos
    - remove_existing_repos

- name: remove current repository files
  file:
    path: /etc/yum.repos.d/{{ item }}
    state: absent
  with_items: "{{ repodircontents.stdout_lines }}"
  ignore_errors: true
  tags:
    - configure_repos
    - remove_existing_repos

- name: Force unregister before register
  redhat_subscription:
    state: absent
  ignore_errors: true

- name: register node with subscription-manager
  redhat_subscription:
    state: present
    username: "{{ rhel_subscription_user }}"
    password: "{{ rhel_subscription_pass }}"
    autosubscribe: false
  register: task_result
  until: task_result | succeeded
  retries: 15
  delay: 10


- name: get correct pool id
  shell: /usr/bin/subscription-manager list --all --available --matches="*{{rhn_pool_id_string}}*" | awk '/Pool ID/ {print $3}' | head -1
  register: pool_id
  ignore_errors: no
  until: pool_id | succeeded
  retries: 15
  delay: 10

- name: attach host to subscription pool
  shell: /usr/bin/subscription-manager attach --pool={{ pool_id.stdout }}
  register: task_result
  until: task_result.rc == 0
  retries: 15
  delay: 10
  ignore_errors: no

## TODO: Will leave for the moment, but should probably use module for this.
## At a minimum, we should add in a "yum clean all". The module
## will handle duplicate packages, residual metadata, etc. The expense
## is that it takes significantly longer.
- name: disable all repos
  command: subscription-manager repos --disable=*

- name: enable repos for rhel
  command: subscription-manager repos --enable "{{ item }}"
  with_items:
    - '{{ rhel_repos }}'
