---
######################### Configure Host Repositories

- name: list current repository files
  shell: "ls -1 /etc/yum.repos.d/"
  register: repodircontents
  tags:
    - configure_repos
    - remove_existing_repos

- name: remove current repository files
  file:
    path: /etc/yum.repos.d/{{ item }}
    state: absent
  with_items: "{{ repodircontents.stdout_lines }}"
  ignore_errors: true
  tags:
    - configure_repos
    - remove_existing_repos


- name: create open.repo template on host
  template:
    src: "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/files/repos_template.j2"
    dest: /etc/yum.repos.d/open_{{ env_type }}.repo
  tags:
   - create_open_repo_template
  ignore_errors: true

##TODO: Is this a left over tag, or does it belong
##to "create open.repo template on host".

- name: remove current repositories
  shell: "yum repolist"
  tags:
    - configure_repos
    - run_yum_repolist
