---

# Plagarized (and modified for this course) from:  https://github.com/nmasse-itix/OpenShift-Lab/tree/master/roles/3scale
# Thank you nmasse-itix !
#
# Use this ansible play for this course only.
# Afterwards, leverage (and contribute to) the original ansible playbook created by nmasse-itix.

- name: "Create project for workload {{ocp_project}}"
  shell: "oc new-project {{ocp_project}} --display-name={{ocp_project}}"
  tags: all

- name: "Label namespace"
  command: "oc label namespace {{ocp_project}} AAD='{{guid}}'"
  tags: all

- name: Make sure we go back do default project
  shell: "oc project default"
  tags: all


################      Multitenent  AMP        #####################

- name: Download {{ threescale_template }}
  get_url:
    url: "{{ threescale_template }}"
    dest: "{{modified_template_path}}"
    force: yes
  tags: all


- name: Process the OpenShift Template and create the OpenShift objects for the 3scale API Management Platform
  shell: |
      oc new-app -f "{{ modified_template_path }}" \
                 -p "ADMIN_PASSWORD={{ amp_admin_passwd }}" \
                 -p "TENANT_NAME={{ocp_project}}" \
                 -p "MASTER_NAME={{ocp_project}}-master" \
                 -p "MASTER_PASSWORD={{master_passwd}}" \
                 -p "MASTER_ACCESS_TOKEN={{master_access_token}}" \
                 -p "WILDCARD_DOMAIN={{ ocp_apps_domain }}" \
                 -n "{{ ocp_project }}" \
                 > {{new_app_output}}
  tags: all

- name: output message
  debug:
    msg: new-app output available at {{new_app_output}}
  tags: all


# #### Storage Tier
- name: "Resume {{with_items}}"
  command: oc rollout resume dc/"{{ item }}" -n "{{ ocp_project }}"
  with_items:
    - backend-redis
    - system-memcache
    - system-mysql
    - system-redis
    - zync-database
  tags: all
- include: wait_for_deploy.yml
  static: no
  vars:
    pod_to_wait:
      - backend-redis
      - system-memcache
      - system-mysql
      - system-redis
      - zync-database
  tags: all


# #### Backend Listeners
- name: "Resume {{with_items}}"
  command: oc rollout resume dc/"{{ item }}" -n "{{ ocp_project }}"
  with_items:
    - backend-listener
    - backend-worker
  tags: all
- include: wait_for_deploy.yml
  static: no
  vars:
    pod_to_wait:
      - backend-listener
      - backend-worker
  tags: all

# #### System Tier
- name: "Resume {{with_items}}"
  command: oc rollout resume dc/"{{ item }}" -n "{{ ocp_project }}"
  with_items:
    - system-app
  tags: all
- include: wait_for_deploy.yml
  static: no
  vars:
    pod_to_wait:
      - system-app
  tags: all

# #### Utility Tier
- name: "Resume {{with_items}}"
  command: oc rollout resume dc/"{{ item }}" -n "{{ ocp_project }}"
  with_items:
    - system-resque
    - system-sidekiq
    - system-sphinx
    - backend-cron
  tags: all
- include: wait_for_deploy.yml
  static: no
  vars:
    pod_to_wait:
      - system-resque
      - system-sidekiq
      - system-sphinx
      - backend-cron
  tags: all


# #### Gateway Tier
- name: "Resume {{with_items}}"
  command: oc rollout resume dc/"{{ item }}" -n "{{ ocp_project }}"
  with_items:
    - apicast-staging
    - apicast-production
    - apicast-wildcard-router
  tags: all
- include: wait_for_deploy.yml
  static: no
  vars:
    pod_to_wait:
      - apicast-staging
      - apicast-production
      - apicast-wildcard-router
  tags: all

# #### Zync / RHSSO Sync Tier
- name: "Resume {{with_items}}"
  command: oc rollout resume dc/"{{ item }}" -n "{{ ocp_project }}"
  with_items:
    - zync
  tags: all
- include: wait_for_deploy.yml
  static: no
  vars:
    pod_to_wait:
      - zync
  tags: all
###################################################################


################        Tenant Rollout        #####################
- name: Copy tenant provisioning script to known path
  template:
    src: templates/create_tenants.sh
    dest: /tmp/create_tenants.sh
    mode: 0755
  tags: all,tenants 
- name: Create tenants
  shell: "/tmp/create_tenants.sh"
  tags: all,tenants 

- name: Creation of tenants complete
  debug:
    msg: Creation of tenants complete.  output files available at {{tenant_output_dir}}
  tags: all,tenants 
###################################################################


- name: workload Tasks Complete
  debug:
    msg: workload Tasks Complete
  tags: all
