---

- name: Configure systemd environment files
  template:
    src: "{{ quay_name }}.j2"
    dest: "{{ systemd_environmenfile_dir}}/{{ quay_name }}"
  notify: "Restart quay service"

- name: Configure systemd unit files
  template:
    src: "{{ quay_service }}.j2"
    dest: "{{ systemd_service_dir}}/{{ quay_service }}"
  notify: "Restart quay service"