# file: pre_software.yml
- name: Pre-Software | Step 000 Pre Software
  hosts: localhost
  connection: local
  become: False
  vars_files:
    - "./env_vars.yml"
    - "./env_secret_vars.yml"
  tags:
    - step003
    - pre_software
  tasks:
    - debug:
        msg: "{{ 'tag_Workshop_' + workshop_prefix }}"


- name: Pre-Software | Setup Ansible Tower Workshop
  hosts: "{{ 'tag_Workshop_' + workshop_prefix }}"
  gather_facts: True
  become: yes
  vars_files:
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_vars.yml"
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_secret_vars.yml"
  roles:
    - { role: "{{ ANSIBLE_REPO_PATH }}/roles/subscription_manager" }
    - { role: "{{ ANSIBLE_REPO_PATH }}/roles/epel"                 }
    - { role: "{{ ANSIBLE_REPO_PATH }}/roles/nodejs"               }
    - { role: "{{ ANSIBLE_REPO_PATH }}/roles/wetty"                }
    - { role: "{{ ANSIBLE_REPO_PATH }}/roles/ansible.tower"        }
    - { role: "{{ ANSIBLE_REPO_PATH }}/roles/zsh"                  }
    # - { role: "{{ ANSIBLE_REPO_PATH }}/roles/cockpit"              }


