- name: Restart Redis Service
  systemd:
    name: "{{ redis_name }}"
    enabled: yes
    state: restarted
    daemon_reload: yes

- name: restart firewalld
  service:
    name: firewalld
    state: restarted

- name: restart iptables
  service:
    name: iptables
    state: restarted